buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath ('com.anatawa12.forge:ForgeGradle:1.2-1.1.+') {
			changing = true
		}
    }
}

apply plugin: 'forge'

// Forge 1.7.10 runs on Java 6 to 8.
sourceCompatibility = 1.8
targetCompatibility = 1.8

version = "0.3.0.0-dev"
group= "com.teamolympus.dangerzone" // https://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "AdventureKraft"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "run"
}

dependencies {

}

processResources {
    inputs.property "version", project.version

    // Replace values in only mcmod.info.
    filesMatching('mcmod.info') 
	{
        expand 'version':project.version
    }
}

jar {
	manifest {
		attributes 'FMLAT' : 'dangerzone_at.cfg'
	}
}

// Ensures that the encoding of source files is set to UTF-8, see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}